### ISSUE TITLE
Choise path to salve dowload content

### ISSUE THREAD

**Issue by victorfernandesraton** [knadh/go-get-youtube#16]
Download function not have options to manage when and where dowload is assigned

**Comment by cofonseca** [comment]
@victorfernandesraton I believe you can handle this by including the full path in the filename. 

For example, if you use this:
`err := vid.Download(0, "C:/Users/jsmith/Downloads/song.mp3", options)`
then you'll find a file called song.mp3 located in C:\Users\jsmith\Downloads.
